name = "hugo-journal"
license = "MIT"
source_repo = ""
description = "Hugo theme based on Twitter BootStrap and Journal CSS theme"
tags = ["post", "category"]
categories = ["featured"]
min_version = 0.14

[author]
    name = "Marco Pas"
    email = "marco.pasopas@gmail.com"